"""Ollama AI client for research summaries and sentiment classification.

Uses a locally running Ollama instance (e.g., qwen2:7b or mistral).
All AI outputs carry a mandatory "not financial advice" disclaimer.
"""
from __future__ import annotations

import logging
from datetime import datetime
from typing import Optional

import httpx

from app.config import get_settings

logger = logging.getLogger(__name__)

DISCLAIMER = (
    "This summary is generated by an AI model for informational purposes only. "
    "It does not constitute financial advice. Please do your own research before "
    "making any investment decisions."
)


class OllamaClient:
    """Async client for Ollama REST API."""

    def __init__(self) -> None:
        settings = get_settings()
        self._base_url = settings.ollama_base_url
        self._model = settings.ollama_model
        self._client = httpx.AsyncClient(timeout=120.0)

    async def _generate(self, prompt: str) -> str:
        try:
            resp = await self._client.post(
                f"{self._base_url}/api/generate",
                json={
                    "model": self._model,
                    "prompt": prompt,
                    "stream": False,
                    "options": {"temperature": 0.3, "num_predict": 512},
                },
            )
            resp.raise_for_status()
            data = resp.json()
            return data.get("response", "").strip()
        except Exception as exc:
            logger.error("Ollama generate failed: %s", exc)
            return ""

    async def investment_summary(
        self,
        symbol: str,
        company_name: str,
        ratios: dict,
        recent_news_headlines: list[str] | None = None,
    ) -> str:
        """Generate a concise investment summary paragraph."""
        news_section = ""
        if recent_news_headlines:
            news_section = "\nRecent news:\n" + "\n".join(f"- {h}" for h in recent_news_headlines[:5])

        prompt = f"""You are a financial research assistant. Based on the following data, write a concise 3–5 sentence investment research summary for {company_name} ({symbol}).

Key financial metrics:
- PE Ratio: {ratios.get('pe', 'N/A')}
- PB Ratio: {ratios.get('pb', 'N/A')}
- ROE: {ratios.get('roe', 'N/A')}%
- ROCE: {ratios.get('roce', 'N/A')}%
- Debt/Equity: {ratios.get('debt_to_equity', 'N/A')}
- Net Margin: {ratios.get('net_margin', 'N/A')}%
- EBITDA Margin: {ratios.get('ebitda_margin', 'N/A')}%
- Revenue CAGR 3Y: {ratios.get('revenue_cagr_3y', 'N/A')}%
- EPS CAGR 3Y: {ratios.get('eps_cagr_3y', 'N/A')}%
{news_section}

Write a factual, balanced summary. Do NOT provide buy/sell recommendations.
Summary:"""
        return await self._generate(prompt)

    async def risk_summary(self, symbol: str, risk_flags: list[dict]) -> str:
        """Generate a risk narrative from risk flags."""
        if not risk_flags:
            return "No significant risk flags detected based on available data."
        flag_lines = "\n".join(
            f"- [{f['severity'].upper()}] {f['label']}: {f['description']}"
            for f in risk_flags
        )
        prompt = f"""You are a financial risk analyst. Summarise the following risk flags for {symbol} in 2–3 sentences:

{flag_lines}

Write a factual, clear risk summary. Do NOT provide investment advice.
Risk Summary:"""
        return await self._generate(prompt)

    async def classify_sentiment(self, headlines: list[str]) -> list[str]:
        """Classify each headline as bullish / bearish / neutral."""
        if not headlines:
            return []
        numbered = "\n".join(f"{i+1}. {h}" for i, h in enumerate(headlines))
        prompt = f"""Classify each news headline below as exactly one of: bullish, bearish, or neutral.
Reply with a numbered list matching the input order, e.g.:
1. bullish
2. neutral
3. bearish

Headlines:
{numbered}

Classifications:"""
        response = await self._generate(prompt)
        results = ["neutral"] * len(headlines)
        for i, line in enumerate(response.strip().splitlines()):
            parts = line.strip().split(".")
            if len(parts) >= 2:
                label = parts[-1].strip().lower()
                if label in ("bullish", "bearish", "neutral") and i < len(headlines):
                    results[i] = label
        return results

    async def explain_filing(self, title: str, excerpt: str) -> str:
        """Explain a filing title / excerpt in plain language."""
        prompt = f"""You are a financial analyst. Explain the following exchange filing in simple language for a retail investor:

Title: {title}
Excerpt: {excerpt[:500] if excerpt else "N/A"}

Explain in 2–3 sentences what this filing means and its potential significance.
Explanation:"""
        return await self._generate(prompt)

    async def quarter_summary(self, symbol: str, latest: dict, prev: dict) -> str:
        """Summarise a quarterly result comparison."""
        def fmt(v: float | None) -> str:
            return f"₹{v/1e7:.2f} Cr" if v else "N/A"

        prompt = f"""Summarise the quarterly results for {symbol}:

Latest quarter:
- Revenue: {fmt(latest.get('revenue'))}
- PAT: {fmt(latest.get('pat'))}
- EBITDA: {fmt(latest.get('ebitda'))}

Previous quarter:
- Revenue: {fmt(prev.get('revenue'))}
- PAT: {fmt(prev.get('pat'))}
- EBITDA: {fmt(prev.get('ebitda'))}

Write a 2–3 sentence factual summary of the quarterly performance.
Summary:"""
        return await self._generate(prompt)

    async def close(self) -> None:
        await self._client.aclose()
